name: surf_flutter_study_jam_2023
description: Surf Flutter Study Jam 2023.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  file_picker: ^5.2.7
  flutter_bloc: ^8.1.1
  bloc: ^8.1.0
  freezed: ^2.3.2
  dio: ^5.1.1
  path_provider: ^2.0.14
  drift: ^2.6.0
  sqlite3_flutter_libs: ^0.5.0
  path: ^1.8.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  json_serializable: ^6.5.4
  drift_dev: ^2.6.0

flutter:
  uses-material-design: true